# Problem 1
Bir YetGenli yeni aldığı bahçesinin etrafına çit çevirmek istiyor. Bahçenin etrafını çit ile çevirmek için gerekli çit uzunluğunu ve bahçenin alanını hesaplayan fonksiyonu yazınız.

In [4]:
def bahce (a,b):
    area= a*b
    perimeter= 2*(a+b)
    return area, perimeter
alan= bahce(5,8)
cevre= bahce(5,8)
print(alan)
print(cevre)

(40, 26)
(40, 26)

# Problem 2
Kendisine gönderilen 2 sayı arasındaki tüm asal sayıları bulan fonksiyonu yazınız.

In [1]:
def asalsayiBul(num1,num2):
    for num in range(num1,num2+1):
        if num>1:
            for i in range(2,num):
                if num%i==0:
                    break
                else:
                    print(num)
asalsayiBul(2,4)

3

# Problem 3
YetGen liderlerinin kurdukları girişim unicorn oluyor. YetGen liderleri iş arkadaşlarının alacağı ücretlerini hesaplamak için bir fonksiyon yazdılar. Bu fonksiyonu kullanarak, YetGen liderlerinin iş arkadaşlarına verecekleri ücretleri hesaplayınız.

Ücret hesaplanması çalışma saatine bağlıdır. Bunun için kullanıcıdan çalışma saati bilgisinn alın. Sonrasında yapılacak ödemenin hesaplanacağı computePay() adlı bir fonksiyon oluşturun. Bu fonksiyonun içinde işlemler yapın. Çalışma saati 40 ve altındaysa saat başına ücret 10 TL’dir. 40 saatin üstünde çalışıldıysa saat başına ücret 15 TL sayılmaktadır.

```
Test etmek için 30 saat değerini giriniz,  sonuç 300 TL çıkmalı, 
ikincil test olarak 50 değerini giriniz,  sonuç 750 TL çıkmalı.
```

In [12]:
saat= int(input("Çalışma saati giriniz:"))
def computePay():
    if saat<40:
        return saat*10
    elif saat>40:
        return saat*15
    else:
        print("Try Again")

pay= computePay()
print(f"total pay:{pay} TL")

total pay:750 TL

# Problem 4
YetGenliler zirveye gitmek için toplanıyor. Zirveye gitmek için kiraladıkları araçlar 4'er kişiliktir. Gelecek kişi sayısı için Airtable üzerinde form açılıyor. Gelecek kişi sayısını alıp dört kişilik araçlara bölüp kalan kişi sayısını döndüren bir fonksiyon yazınız.

In [21]:
kisiSayisi= int(input("Gelecel kişi sayısını giriniz:"))
def zirve():
  kalan= kisiSayisi//4
  if kisiSayisi%4!=0:
    return kalan
    
   

  
print(zirve())

1

# Problem 5
sayiTopla() adında bir fonksiyon yazın. sayiTopla() fonksiyonu girilen sayıları toplayarak yazdırmasını sağlayan bir fonksiyon yazınız.

Örneğin sayiTopla(1,2,3,4,5) yazdığımızda 15 çıktısını almalıyız. sayiTopla(1,2,3,4,5,6,7,8,9,10) yazdığımızda 55 çıktısını almalıyız.

In [28]:
def sayiTopla(*args):
    return sum(args)

print(sayiTopla(1, 2, 3, 4, 5))      
print(sayiTopla(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))

15
55

# Problem 6

[("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)] listesi içerisinde verilen elemanların her birini tuple içindeki 2. Elemana göre sıralayınız.

In [2]:
data=[("xxx",1),("xxx",2),("xxx",9),("xxx",3),("xxx",1),("xxx",13),("xxx",26),("xxx",4)]
data.sort(key=lambda tup:tup[1])
print(data)

[('xxx', 1), ('xxx', 1), ('xxx', 2), ('xxx', 3), ('xxx', 4), ('xxx', 9), ('xxx', 13), ('xxx', 26)]

# Problem 7
List comprehension kullanarak 1'den 100'e kadar olan sayılardan sadece çift sayıları bir listeye atmayı yapmayı çalışın.

In [30]:
cift = [x for x in range(1, 101) if x % 2 == 0]
print(cift)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]